import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient({
  datasources: { db: { url: process.env.DIRECT_URL ?? process.env.DATABASE_URL } },
});

const categories = [
  { name: "Visage", slug: "visage", icon: "✨", description: "Nettoyants, crèmes, sérums, anti-âge, soins yeux", order: 1, isActive: true },
  { name: "Corps", slug: "corps", icon: "🧴", description: "Hydratants, gommages, huiles, soins mains et pieds", order: 2, isActive: true },
  { name: "Cheveux", slug: "cheveux", icon: "💇", description: "Shampoings, soins, colorations, accessoires", order: 3, isActive: true },
  { name: "Hygiène", slug: "hygiene", icon: "🪥", description: "Bain & douche, soins dentaires, déodorants, hygiène intime", order: 4, isActive: true },
  { name: "Santé", slug: "sante", icon: "❤️", description: "Premiers secours, matériel médical, santé de la peau", order: 5, isActive: true },
  { name: "Compléments alimentaires", slug: "complements-alimentaires", icon: "💊", description: "Vitamines, minéraux, probiotiques, minceur, énergie", order: 6, isActive: true },
  { name: "Bébé", slug: "bebe", icon: "🍼", description: "Soins bébé, puériculture, maternité, alimentation", order: 7, isActive: true },
  { name: "Bio & Naturel", slug: "bio", icon: "🌿", description: "Cosmétiques bio, aromathérapie, produits naturels certifiés", order: 8, isActive: true },
  { name: "Solaires", slug: "solaires", icon: "☀️", description: "Crèmes solaires, après-soleil, autobronzants", order: 9, isActive: true },
];

const products = [
  // ─── VISAGE ───────────────────────────────────────────
  {
    name: "Anthelios Uvmune 400 SPF50+ Fluide",
    slug: "anthelios-uvmune-spf50-fluide",
    brand: "La Roche-Posay",
    price: 18.50,
    comparePrice: 24.00,
    stock: 55,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Protection solaire visage très haute SPF50+, peaux normales à mixtes",
    description: "Anthelios UVmune 400 offre la plus haute protection contre les UVA longs jamais atteinte. Formule ultra-légère, résistante à l'eau, sans parfum.",
    usageAdvice: "Appliquer 30 min avant exposition, renouveler toutes les 2h.",
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop"],
    tags: ["SPF50", "solaire", "visage", "La Roche-Posay"],
    categorySlug: "visage",
  },
  {
    name: "Eau Thermale Spray 300ml",
    slug: "eau-thermale-spray-300ml",
    brand: "Avène",
    price: 8.90,
    stock: 120,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Spray d'eau thermale apaisante pour peaux sensibles et réactives",
    description: "L'Eau Thermale Avène est une eau de source naturelle enrichie en oligo-éléments. Elle apaise et adoucit les peaux les plus sensibles.",
    usageAdvice: "Vaporiser sur visage propre à tout moment de la journée. Laisser agir et tamponner l'excès.",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop"],
    tags: ["eau thermale", "apaisant", "sensible", "Avène"],
    categorySlug: "visage",
  },
  {
    name: "Sébium Pore Refiner 30ml",
    slug: "sebium-pore-refiner-30ml",
    brand: "Bioderma",
    price: 15.90,
    comparePrice: 19.00,
    stock: 40,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Soin correcteur de pores pour peaux grasses et mixtes",
    description: "Bioderma Sébium Pore Refiner resserre les pores dilatés et unifie le teint. Sa texture légère matifie et lisse le grain de peau.",
    usageAdvice: "Appliquer matin et/ou soir sur visage propre, seul ou sous votre crème.",
    images: ["https://images.unsplash.com/photo-1601049541271-f2e9bf7d9c2d?w=400&h=400&fit=crop"],
    tags: ["pores", "matifiant", "mixte", "Bioderma"],
    categorySlug: "visage",
  },
  {
    name: "Liftactiv Collagen Specialist",
    slug: "liftactiv-collagen-specialist",
    brand: "Vichy",
    price: 34.00,
    stock: 30,
    isActive: true, isFeatured: true, isNew: true, isPromotion: false,
    shortDescription: "Sérum anti-âge boosteur de collagène, fermeté et éclat visible",
    description: "Liftactiv Collagen Specialist combine 2 formes de collagène et de la vitamine C pour une action anti-rides et repulpante visible dès 4 semaines.",
    usageAdvice: "Appliquer matin et soir sur visage et cou avant votre crème habituelle.",
    images: ["https://images.unsplash.com/photo-1556909045-2b2a1a462789?w=400&h=400&fit=crop"],
    tags: ["collagène", "anti-âge", "sérum", "Vichy"],
    categorySlug: "visage",
  },
  {
    name: "Hydraphase Intense Légère",
    slug: "hydraphase-intense-legere",
    brand: "La Roche-Posay",
    price: 19.90,
    stock: 45,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Crème hydratante intense longue durée pour peaux déshydratées",
    description: "Hydraphase Intense Légère offre 48h d'hydratation intense. Sa texture légère convient aux peaux normales à mixtes déshydratées.",
    usageAdvice: "Appliquer matin et soir sur peau propre. Peut être utilisée sous le maquillage.",
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop"],
    tags: ["hydratant", "intense", "longue durée", "La Roche-Posay"],
    categorySlug: "visage",
  },
  // ─── CORPS ────────────────────────────────────────────
  {
    name: "Huile Bio Sèche Multi-Usages",
    slug: "huile-bio-seche-multi-usages",
    brand: "Nuxe",
    price: 22.50,
    comparePrice: 28.00,
    stock: 50,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Huile sèche prodigieuse pour corps, visage et cheveux, parfum fleuri",
    description: "L'Huile Prodigieuse de Nuxe est une huile sèche multi-usages enrichie en 6 huiles végétales précieuses. Elle nourrit et illumine la peau du corps, du visage et les cheveux.",
    usageAdvice: "Appliquer sur peau sèche après la douche. Peut aussi être ajoutée à l'eau du bain.",
    images: ["https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop"],
    tags: ["huile", "corps", "cheveux", "Nuxe"],
    categorySlug: "corps",
  },
  {
    name: "Lipikar Lait Corps AP+M",
    slug: "lipikar-lait-corps-apm",
    brand: "La Roche-Posay",
    price: 12.50,
    stock: 70,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Lait relipidant corps pour peaux sèches à très sèches, 400ml",
    description: "Lipikar Lait AP+M restaure la barrière cutanée et apaise les démangeaisons. Formule enrichie en Beurre de Karité et en eau thermale de La Roche-Posay.",
    usageAdvice: "Appliquer sur corps propre et séché, matin et soir ou après chaque douche.",
    images: ["https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop"],
    tags: ["lait corps", "sec", "apaisant", "La Roche-Posay"],
    categorySlug: "corps",
  },
  {
    name: "Gommage Corps Sucre & Café",
    slug: "gommage-corps-sucre-cafe",
    brand: "Nuxe",
    price: 11.90,
    comparePrice: 14.50,
    stock: 35,
    isActive: true, isFeatured: false, isNew: true, isPromotion: true,
    shortDescription: "Gommage corps exfoliant doux, éclat immédiat et peau lisse",
    description: "Ce gommage fondant révèle une peau douce et lumineuse grâce à ses grains de sucre de canne et d'huile de café. Parfum gourmand et enveloppant.",
    usageAdvice: "Appliquer sur peau humide en massages circulaires, rincer abondamment. 1 à 2 fois par semaine.",
    images: ["https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop"],
    tags: ["gommage", "exfoliant", "corps", "éclat"],
    categorySlug: "corps",
  },
  {
    name: "Bio-Oil Huile Spécialisée 125ml",
    slug: "bio-oil-huile-specialisee-125ml",
    brand: "Bio-Oil",
    price: 16.90,
    comparePrice: 20.00,
    stock: 45,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Huile multi-usages pour cicatrices, vergetures et imperfections",
    description: "Bio-Oil aide à améliorer l'apparence des cicatrices, vergetures et inégalités de teint. Enrichie en vitamines A et E et en PurCellin Oil.",
    usageAdvice: "Masser sur les zones concernées deux fois par jour pendant 3 mois minimum.",
    images: ["https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop"],
    tags: ["huile", "cicatrices", "vergetures", "Bio-Oil"],
    categorySlug: "corps",
  },
  // ─── CHEVEUX ──────────────────────────────────────────
  {
    name: "Shampoing Extra-Doux Céramides",
    slug: "shampoing-extra-doux-ceramides",
    brand: "Klorane",
    price: 7.90,
    stock: 85,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Shampoing quotidien doux aux céramides pour cheveux fragilisés",
    description: "Le Shampoing Extra-Doux Klorane fortifie et protège les cheveux fragilisés grâce aux céramides végétaux. Convient à une utilisation quotidienne.",
    usageAdvice: "Appliquer sur cheveux mouillés, masser délicatement le cuir chevelu, rincer.",
    images: ["https://images.unsplash.com/photo-1626170620573-6c2a8e0fb879?w=400&h=400&fit=crop"],
    tags: ["shampoing", "céramides", "quotidien", "Klorane"],
    categorySlug: "cheveux",
  },
  {
    name: "Elixir Ultime Huile Légendaire",
    slug: "elixir-ultime-huile-legendaire",
    brand: "Kérastase",
    price: 38.00,
    comparePrice: 45.00,
    stock: 20,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Huile capillaire luxueuse pour tous types de cheveux, brillance intense",
    description: "L'Élixir Ultime de Kérastase combine 4 huiles précieuses — Marula, Argan, Caméllia et Jasmin — pour transformer tous les types de cheveux en une crinière soyeuse et brillante.",
    usageAdvice: "Appliquer quelques gouttes sur cheveux humides ou secs avant ou après coiffage.",
    images: ["https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop"],
    tags: ["huile", "brillance", "cheveux", "Kérastase"],
    categorySlug: "cheveux",
  },
  {
    name: "Soin Cheveux Intensif Masque Kératine",
    slug: "soin-cheveux-masque-keratine",
    brand: "Ducray",
    price: 14.50,
    stock: 30,
    isActive: true, isFeatured: false, isNew: true, isPromotion: false,
    shortDescription: "Masque fortifiant à la kératine pour cheveux cassants et abîmés",
    description: "Le Masque Kératine Ducray reconstruit les fibres capillaires fragilisées en profondeur. Sa formule enrichie en kératine et en protéines végétales renforce et assouplit les cheveux.",
    usageAdvice: "Appliquer après shampoing sur cheveux essorés, laisser poser 5 min, rincer.",
    images: ["https://images.unsplash.com/photo-1626170620573-6c2a8e0fb879?w=400&h=400&fit=crop"],
    tags: ["masque", "kératine", "réparation", "Ducray"],
    categorySlug: "cheveux",
  },
  // ─── HYGIÈNE ──────────────────────────────────────────
  {
    name: "Elgydium Dentifrice Anti-Plaque",
    slug: "elgydium-dentifrice-anti-plaque",
    brand: "Elgydium",
    price: 4.20,
    stock: 150,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Dentifrice anti-plaque et anti-tartre pour une hygiène bucco-dentaire optimale",
    description: "Elgydium Anti-Plaque élimine efficacement la plaque dentaire et protège des caries. Sa formule au chlorhexidine inhibe la formation du tartre.",
    usageAdvice: "Se brosser les dents 2 à 3 fois par jour après les repas pendant 2 minutes.",
    images: ["https://images.unsplash.com/photo-1556909045-2b2a1a462789?w=400&h=400&fit=crop"],
    tags: ["dentifrice", "plaque", "caries", "Elgydium"],
    categorySlug: "hygiene",
  },
  {
    name: "Déodorant 48h Efficacité Clinique",
    slug: "deodorant-48h-efficacite-clinique",
    brand: "Vichy",
    price: 8.90,
    comparePrice: 11.00,
    stock: 90,
    isActive: true, isFeatured: false, isNew: false, isPromotion: true,
    shortDescription: "Déodorant optimal tolérance pour peaux normales, sans alcool",
    description: "Vichy Homme Optimal Tolérance offre une efficacité anti-transpirante 48h sans alcool ni parfum. Idéal pour les peaux sensibles et fraîchement épilées.",
    usageAdvice: "Appliquer sur aisselles propres et sèches. Peut être utilisé immédiatement après rasage ou épilation.",
    images: ["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop"],
    tags: ["déodorant", "48h", "sans alcool", "Vichy"],
    categorySlug: "hygiene",
  },
  {
    name: "Gel Douche Doux pH Neutre",
    slug: "gel-douche-doux-ph-neutre",
    brand: "Uriage",
    price: 6.50,
    stock: 100,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Gel douche surgras pour peaux sensibles et atopiques, pH neutre",
    description: "Uriage Gel Douche nettoie en douceur sans altérer le film hydrolipidique. Sa formule enrichie en Eau Thermale d'Uriage respecte l'équilibre naturel de la peau.",
    usageAdvice: "Appliquer sur corps mouillé en massant délicatement, rincer soigneusement.",
    images: ["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop"],
    tags: ["gel douche", "doux", "pH neutre", "Uriage"],
    categorySlug: "hygiene",
  },
  // ─── SANTÉ ────────────────────────────────────────────
  {
    name: "Arnica Montana Gel Anti-Douleur",
    slug: "arnica-montana-gel-anti-douleur",
    brand: "Boiron",
    price: 7.50,
    stock: 60,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Gel à l'arnica pour soulager hématomes, contusions et douleurs musculaires",
    description: "Arnicare Gel de Boiron soulage naturellement les douleurs musculaires, les hématomes et les contusions. Sa texture gel non grasse pénètre rapidement.",
    usageAdvice: "Appliquer 3 fois par jour sur la zone douloureuse en massant légèrement.",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop"],
    tags: ["arnica", "douleur", "hématome", "Boiron"],
    categorySlug: "sante",
  },
  {
    name: "Thermomètre Infrarouge Sans Contact",
    slug: "thermometre-infrarouge-sans-contact",
    brand: "Microlife",
    price: 32.00,
    comparePrice: 42.00,
    stock: 25,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Thermomètre frontal précis et rapide, résultat en 1 seconde",
    description: "Le thermomètre infrarouge Microlife mesure la température en 1 seconde sans contact. Parfait pour les enfants. Mémoire des 30 dernières mesures.",
    usageAdvice: "Placer à 3–5 cm du front, appuyer sur le bouton et lire la mesure affichée.",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop"],
    tags: ["thermomètre", "sans contact", "enfant", "Microlife"],
    categorySlug: "sante",
  },
  {
    name: "Pansements Aqua Protect Waterproof",
    slug: "pansements-aqua-protect-waterproof",
    brand: "Urgo",
    price: 5.90,
    stock: 200,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Pansements waterproof transparents, résistants à l'eau et à la douche",
    description: "Les pansements Urgo Aqua Protect résistent à l'eau et à la transpiration. Transparents et discrets, ils favorisent la cicatrisation en milieu humide.",
    usageAdvice: "Nettoyer et désinfecter la plaie avant application. Changer toutes les 48-72h.",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop"],
    tags: ["pansement", "waterproof", "cicatrisation", "Urgo"],
    categorySlug: "sante",
  },
  // ─── COMPLÉMENTS ALIMENTAIRES ─────────────────────────
  {
    name: "Oméga-3 Haute Concentration 60 caps",
    slug: "omega-3-haute-concentration-60-caps",
    brand: "Pileje",
    price: 28.00,
    stock: 35,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Acides gras oméga-3 EPA/DHA pour cœur, cerveau et articulations",
    description: "Formule haute concentration en EPA et DHA issus d'huiles de poisson certifiées. Contribue au fonctionnement normal du cœur et du cerveau.",
    usageAdvice: "Prendre 2 capsules par jour pendant le repas. Conserver au frais après ouverture.",
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop"],
    tags: ["oméga-3", "coeur", "cerveau", "Pileje"],
    categorySlug: "complements-alimentaires",
  },
  {
    name: "Magnésium Marin + Vitamine B6",
    slug: "magnesium-marin-vitamine-b6",
    brand: "Arkopharma",
    price: 14.90,
    comparePrice: 18.00,
    stock: 55,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Complément anti-stress et anti-fatigue, 60 comprimés",
    description: "Association synergique de magnésium marin hautement absorbable et de vitamine B6. Réduit la fatigue et contribue au bon fonctionnement du système nerveux.",
    usageAdvice: "Prendre 2 comprimés par jour avec un verre d'eau pendant le repas.",
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop"],
    tags: ["magnésium", "stress", "fatigue", "Arkopharma"],
    categorySlug: "complements-alimentaires",
  },
  {
    name: "Lactibiane Référence 30 gélules",
    slug: "lactibiane-reference-30-gelules",
    brand: "Pileje",
    price: 22.50,
    stock: 40,
    isActive: true, isFeatured: false, isNew: true, isPromotion: false,
    shortDescription: "Probiotiques de référence pour équilibre du microbiote intestinal",
    description: "Lactibiane Référence combine 5 souches probiotiques sélectionnées cliniquement pour maintenir l'équilibre du microbiote intestinal. Contribue à l'immunité.",
    usageAdvice: "1 gélule par jour le matin à jeun avec un grand verre d'eau. Conserver au réfrigérateur.",
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop"],
    tags: ["probiotiques", "microbiote", "intestin", "Pileje"],
    categorySlug: "complements-alimentaires",
  },
  // ─── BÉBÉ ─────────────────────────────────────────────
  {
    name: "Lait Corps Bébé Hydratant Doux",
    slug: "lait-corps-bebe-hydratant-doux",
    brand: "Mustela",
    price: 9.90,
    stock: 65,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Lait corps quotidien pour bébé, formule ultra-douce dès la naissance",
    description: "Mustela Lait Corps hydrate et nourrit la peau délicate de bébé. Sa formule ultra-douce avec de l'avocado perseose protège le microbiome de la peau du nourrisson.",
    usageAdvice: "Appliquer après le bain sur tout le corps de bébé en massages doux.",
    images: ["https://images.unsplash.com/photo-1591969568428-c2a84e37de3a?w=400&h=400&fit=crop"],
    tags: ["bébé", "lait corps", "doux", "Mustela"],
    categorySlug: "bebe",
  },
  {
    name: "Crème Solaire Bébé SPF50+ 100ml",
    slug: "creme-solaire-bebe-spf50-100ml",
    brand: "Avène",
    price: 12.90,
    comparePrice: 16.00,
    stock: 40,
    isActive: true, isFeatured: true, isNew: false, isPromotion: true,
    shortDescription: "Crème solaire SPF50+ pour bébé et enfant, résistante eau et sable",
    description: "Avène Solaire Enfant SPF50+ offre une protection très haute dès le plus jeune âge. Formule sans parfum, sans paraben, testée sur peaux atopiques.",
    usageAdvice: "Appliquer généreusement 30 min avant exposition. Renouveler toutes les 2h et après chaque baignade.",
    images: ["https://images.unsplash.com/photo-1591969568428-c2a84e37de3a?w=400&h=400&fit=crop"],
    tags: ["solaire", "bébé", "SPF50", "Avène"],
    categorySlug: "bebe",
  },
  // ─── BIO ──────────────────────────────────────────────
  {
    name: "Huile Essentielle Lavande Officinale",
    slug: "huile-essentielle-lavande-officinale",
    brand: "Puressentiel",
    price: 9.50,
    stock: 75,
    isActive: true, isFeatured: false, isNew: false, isPromotion: false,
    shortDescription: "Huile essentielle 100% pure et naturelle, apaisante et relaxante",
    description: "L'huile essentielle de Lavande Officinale Puressentiel est 100% pure, naturelle et chémotypée. Elle favorise la détente, améliore le sommeil et apaise les irritations cutanées.",
    usageAdvice: "En diffusion : 5 à 10 gouttes dans un diffuseur. En application : 2 gouttes mélangées à une huile végétale.",
    images: ["https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop"],
    tags: ["lavande", "huile essentielle", "relaxant", "Puressentiel"],
    categorySlug: "bio",
  },
  {
    name: "Crème Visage Bio Hydratante",
    slug: "creme-visage-bio-hydratante",
    brand: "Caudalie",
    price: 19.00,
    comparePrice: 24.00,
    stock: 30,
    isActive: true, isFeatured: true, isNew: true, isPromotion: true,
    shortDescription: "Crème bio certifiée, hydratation 24h, éclat naturel, peaux normales",
    description: "La Crème Hydratante Bio Caudalie est certifiée bio par COSMOS. Enrichie en polyphénols de raisin antioxydants et en hyaluronique, elle hydrate et protège la peau.",
    usageAdvice: "Appliquer matin et soir sur visage propre. Parfaite base de maquillage.",
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop"],
    tags: ["bio", "hydratant", "visage", "Caudalie"],
    categorySlug: "bio",
  },
  // ─── SOLAIRES ─────────────────────────────────────────
  {
    name: "Ambre Solaire SPF50 Lait Corps",
    slug: "ambre-solaire-spf50-lait-corps",
    brand: "Garnier",
    price: 10.90,
    comparePrice: 13.50,
    stock: 65,
    isActive: true, isFeatured: false, isNew: false, isPromotion: true,
    shortDescription: "Lait solaire SPF50 corps hydratant, résistant eau, 400ml",
    description: "Ambre Solaire de Garnier protège efficacement contre les UVA et UVB. Sa formule enrichie en vitamine E antioxydante maintient la peau hydratée et résiste à l'eau.",
    usageAdvice: "Appliquer avant l'exposition, renouveler toutes les 2h et après chaque bain.",
    images: ["https://images.unsplash.com/photo-1591969568428-c2a84e37de3a?w=400&h=400&fit=crop"],
    tags: ["solaire", "SPF50", "corps", "Garnier"],
    categorySlug: "solaires",
  },
  {
    name: "After Sun Réparateur Apaisant",
    slug: "after-sun-reparateur-apaisant",
    brand: "Vichy",
    price: 13.90,
    stock: 45,
    isActive: true, isFeatured: false, isNew: true, isPromotion: false,
    shortDescription: "Soin après-soleil réparateur et apaisant, coups de soleil et rougeurs",
    description: "Vichy Idéal Soleil After Sun calme et répare la peau après l'exposition. Sa formule hydratante à l'eau thermale de Vichy prolonge le bronzage et apaise les coups de soleil.",
    usageAdvice: "Appliquer généreusement après chaque exposition solaire sur peau propre.",
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop"],
    tags: ["après-soleil", "apaisant", "réparateur", "Vichy"],
    categorySlug: "solaires",
  },
];

async function main() {
  console.log("🌱 Début du seeding Boticinal-style...");

  const hashedPassword = await bcrypt.hash(process.env.ADMIN_PASSWORD ?? "Admin@2024!", 12);
  const admin = await prisma.admin.upsert({
    where: { email: process.env.ADMIN_EMAIL ?? "admin@parapharmacie.fr" },
    update: {},
    create: { email: process.env.ADMIN_EMAIL ?? "admin@parapharmacie.fr", password: hashedPassword, name: "Administrateur" },
  });
  console.log("✅ Admin:", admin.email);

  const createdCategories: Record<string, string> = {};
  for (const cat of categories) {
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, icon: cat.icon, description: cat.description, order: cat.order },
      create: cat,
    });
    createdCategories[cat.slug] = created.id;
  }
  console.log(`✅ ${categories.length} catégories`);

  let count = 0;
  for (const product of products) {
    const { categorySlug, ...data } = product;
    const categoryId = createdCategories[categorySlug];
    if (!categoryId) { console.warn(`⚠️ Catégorie manquante: ${categorySlug}`); continue; }
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: { ...data, categoryId, weight: null, reference: null },
    });
    count++;
  }
  console.log(`✅ ${count} produits`);
  console.log("\n🎉 Seeding terminé !");
}

main()
  .catch((e) => { console.error("❌", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
